version: '3'
services:
  nginx:
    image: nginx:1.14.0-alpine
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./index.html:/var/www/index.html:ro

