input_length: 128
forecast_length: 64

random_seed: 0
batch_size: 64
early_stop: True
min_epochs: 10
max_epochs: 1000

num_workers: 4
save_top_k: 5
row_log_interval: 1000
progress_bar_refresh_rate: 100

network_name: "SimpleLSTM"
network_params: {}

log_dir: "simple_lstm"
