version: "3"
services:
  dev:
    container_name: caddi2018-dev
    network_mode: none
    image: iimuz/cpp-dev:v3.8.0-atcoder1
    environment:
      USER_ID: $USER_ID
      GROUP_ID: $GROUP_ID
      TZ: $TIME_ZONE
    volumes:
      - src:/src/github.com/iimuz/atcoder
    working_dir: /src/github.com/iimuz/atcoder/CADDi2018_beginners
    command: ash

volumes:
  src:
    driver_opts:
      type: none
      device: ${PWD}/../../../
      o: bind
