version: "3.4"
services:
  samba:
    image: dperson/samba:latest
    environment:
       TZ: Asia/Tokyo
    ports:
      - 137:137/udp
      - 138:138/udp
      - 139:139/tcp
      - 445:445/tcp
    restart: unless-stopped
    volumes:
      - ~/src:/mnt
    command: '-s "ubuntu;/mnt;yes;no;yes;all;none;*;ubuntu"'

