version: "2.3"
services:
  run:
    container_name: grpc-run
    image: buildpack-deps:stretch-scm
    volumes:
      - src:/opt/bin:ro
    working_dir: /opt/bin
    command: bash -c "LD_LIBRARY_PATH=. ./greeter_server"

volumes:
  src:
    driver_opts:
      type: none
      device: ${PWD}/../../../bin
      o: bind
