version: "2"
services:
  dev:
    container_name: atcoder-dev
    image: localhost:cpp
    environment:
      USER_ID: ${USER_ID}
      GROUP_ID: ${GROUP_ID}
      TZ: ${TIME_ZONE}
    volumes:
      - src:/src/github.com/iimuz/atcoder
    working_dir: /src/github.com/iimuz/atcoder/ABC087B_coins
    command: ash

volumes:
  src:
    driver_opts:
      type: none
      device: ${PWD}/../../../
      o: bind
