version: "2"
services:
  dev:
    image: localhost:godev
    environment:
      USER_ID: ${USER_ID}
      GROUP_ID: ${GROUP_ID}
      TZ: ${TIME_ZONE}
    ports:
      - 127.0.0.1:4000:4000
    volumes:
      - src:/go/src/gitlab.com/iimuz/go-vue-example
    working_dir: /go/src/gitlab.com/iimuz/go-vue-example
    command: ash

volumes:
  src:
    driver_opts:
      type: none
      device: ${PWD}/../../../
      o: bind
