version: '2'
services:
  dev:
    image: iimuz/golang-dev:v1.9.2-1.1.0
    environment:
      TZ: Asia/Tokyo
      HTTP_PROXY: ${HTTP_PROXY}
      http_proxy: ${HTTPS_PROXY}
      HTTPS_PROXY: ${HTTP_PROXY}
      https_proxy: ${HTTPS_PROXY}
    volumes:
      - ..:/go/src/github.com/iimuz/ipc-samples:rw
    working_dir: /go/src/github.com/iimuz/ipc-samples/shm-go
    entrypoint: bash
