version: "3.3"
services:
  nvim:
    container_name: abc113c-editor
    network_mode: none
    image: iimuz/neovim:v0.3.0-cpp7
    environment:
      USER_ID: ${USER_ID}
      GROUP_ID: ${GROUP_ID}
      TZ: ${TIME_ZONE}
    volumes:
      - at-tenka1-a-src:/src/github.com/iimuz/atcoder
    working_dir: /src/github.com/iimuz/atcoder/ABC113/C

volumes:
  src:
    driver_opts:
      type: none
      device: ${PWD}/../../../../
      o: bind
