version: "2"
services:
  upload:
    build:
      context: .
      dockerfile: Dockerfile
    user: $USER_ID:$GROUP_ID
    volumes:
      - .:/workspace:rw
    working_dir: /workspace
    command: /bin/bash

